name: example
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  http_annotations:
    path: ../../http_annotations

dev_dependencies:
  build_runner: 2.1.4
  http_gen:
    path: ../../http_gen
